# Base image with Node
FROM node:18-alpine

# Set working directory inside container
WORKDIR /app

# Copy package.json & package-lock.json first (better for caching)
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the app files
COPY . .

# Expose port (must match app.js)
EXPOSE 5000

# Start the app
CMD ["npm", "start"]

